### ISSUE TITLE
wifi not as useful as battery meter - option to choose?

### ISSUE THREAD

**Issue by joelanman** [googlecreativelab/meter#10]
Love this, first live wallpaper I've used in years. However, it used to have the option to choose which values you want to display. I had mine just set to battery - it's the only really useful one for me. Since updating, I no longer have the option to choose. I can turn off the notifications mode, but it still shows wifi sometimes which isn't useful to me.

**Comment by hapticdata** [comment]
this feature is now available. The change is reflected in the repo and is live in the play store.

**Comment by joelanman** [comment]
Awesome, thanks!
