### ISSUE TITLE
The shape is too large in landscape mode

### ISSUE THREAD

**Issue by tsekityam** [googlecreativelab/meter#12]
As you can see in the following screenshot, the shape is too large and the label of the shape is below the visible area.

![screenshot_2015-10-18-13-24-06](https://cloud.githubusercontent.com/assets/3814422/10562710/2d2e326a-759c-11e5-9a41-6692adb3eda7.png)

Device: Nexus 7 2013 with Android 5.1.1

**Comment by hapticdata** [comment]
this was fixed and is also live in the play store
