### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by albinekb** [googlecreativelab/meter#13]
Seems like developers hasn't been her for nearly a month..

**Comment by hapticdata** [comment]
not sure why you would say that? A new version is now fully distributed in the play store.

**Comment by albinekb** [comment]
Now then? @hapticdata

**Comment by hapticdata** [comment]
@albinekb No, this project has not been abandoned. We are currently occupied with other projects but Meter is still alive and well.

**Comment by albinekb** [comment]
@hapticdata dead? :dancer:
