### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by zetrozky** [googlecreativelab/meter#2]
The app keeps force closing on my tablet.

**Comment by albinekb** [comment]
@ZelectroKarZ which device? Which android version?

**Comment by zetrozky** [comment]
Samsung Galaxy Tab 4 7.0 on Android KitKat 4.4.2

**Comment by albinekb** [comment]
What launcher are you using on these devices? @ZelectroKarZ

**Comment by zetrozky** [comment]
Google now launcher on both devices

**Comment by subbuboyapati** [comment]
same problem i am also facing. I am using Mi3 MIUI7 android version 4.4.4 kitkat

**Comment by hapticdata** [comment]
@subbuboyapati @ZelectroKarZ have either of you tried the code that is the latest in this repository 28161fede? It should be fixed here on github. Play store update is on the way.

**Comment by zetrozky** [comment]
How do you do that? ( I got a play update today to 1.0.1... I'm going to test it now... )

**Comment by zetrozky** [comment]
It's working!
