### ISSUE TITLE
Inaccurate Notification Count

### ISSUE THREAD

**Issue by karite36** [googlecreativelab/meter#7]
Android Version: 6.0
Device: Nexus 6
Issue: Even when I have 0 notifications in my notification bar it still lists two. In fact it appears to have an offset of 2 in all cases. II, in fact, just saw it turn to 3 when I received a single notification. 

Correction: On further inspection, it seems to count ANYTHING in the notification drawer as a notification. It counts my music player, and the presence of Facebook Chat Heads, as notification. Those aren't notifications. One is a quick-control and the other is just a count of how many Heads are active. 

Please fix this, thanks. I'd try and help but I don't know Java, just C++.

**Comment by wasdennnoch** [comment]
I'm having the issue that no notifications are found, it constantly shows 0 as the notification count.

**Comment by karite36** [comment]
That's weird. For me it shows EVERYTHING in the system tray as a
notification.

**Comment by wasdennnoch** [comment]
Hm. Either way it isn't working as intended.

**Comment by karite36** [comment]
Yeah, not cool

**Comment by hapticdata** [comment]
as you can see, we are merely listening for notifications and keeping a counter:

https://github.com/googlecreativelab/meter/blob/master/app/src/main/java/com/androidexperiments/meter/NotificationService.java#L75

It shows up as a notification if it is returned from the systems call to `getActiveNotifications()`

@karite36 Music Player and Chat Heads and several other apps are notifications in this sense. It would be simple enough to filter out your use-case in the function I linked to.

@wasdennnoch You are seeing zero notifications when you do have some? I remember you were having a problem with the app. Did you ever give notifications its proper permission? If you go to **Settings -> Sound & Notification -> notification access**, please make sure Meter is checked as having permission

**Comment by karite36** [comment]
I assumed so. There should be a distinction between passive and active
notifications. Music Player's being passive in this case.

**Comment by wasdennnoch** [comment]
After digging deep in the Samsung-modified settings it works! Thanks!  (The notification options aren't even translated on my device,  thanks Samsung...)
