### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by wasdennnoch** [googlecreativelab/meter#9]
The app crashes every time I launch it.
Stack trace extract:

http://puu.sh/kGgLy/1c7c22f4e8.png
http://puu.sh/kGgMW/977a127df4.png

Device: SGS3, 4.3.

**Comment by hapticdata** [comment]
Hi, @wasdennnoch have you tried compiling the current master branch on your device? This issue should be resolved with 28161fedebc

**Comment by wasdennnoch** [comment]
In think the problem is that you are using the method "getDrawable(int, Theme)" that is available on devices with API level >=22, you should use the

**Comment by wasdennnoch** [comment]
damit Phone...

...the method getDrawable(int) instead or use ContextCompat.getDrawable(context, R.drawable.***) (See http://stackoverflow.com/questions/29041027/android-getresources-getdrawable-deprecated-api-22)

**Comment by hapticdata** [comment]
@wasdennnoch Are you using the version currently in the play store (`1.0`)? I don't believe the the latest in this repo (28161fe) uses `getDrawable`

I believe this error is fixed in this repo. If it isn't that would be good to know.

**Comment by wasdennnoch** [comment]
I'm using the version from the play store, wouldn't it be a good idea to update the play store version? This would help all the other people who have the same problem, and nobody would have to compile the source for himself.

**Comment by hapticdata** [comment]
@wasdennnoch for sure, thats the plan

**Comment by wasdennnoch** [comment]
Nice, is there already a fixed date when the update will be released? Or in other words, what  are you wating for? :D
